### ISSUE TITLE
Npgsql critical vulnerability to SQL Injection via Protocol Message Size Overflow

### ISSUE THREAD

**Issue by guillaume-raineri** [Dartanlla/OWS#144]
Hi there :) 

While installing OWS, I found out that there is a critical vulnerability that you can found here : https://github.com/advisories/GHSA-x9vc-6hfv-hg8c

Just to let you know.

Keep up the good work!

**Comment by SloppyShovel** [comment]
Thanks for letting us know, PostgreSQL and MySQL are currently not working as we are working on some internal changes, PostgreSQL will be default supported DB in the future instead of MSSQL as before PostgreSQL and MySQL were done by the community, once the internal changes are done the PostgreSQL dependency will be updated :)

**Comment by SloppyShovel** [comment]
#142 Updates the dependencies but like i said it doesn't work currently due to internal changes

Hope that helps

**Comment by SloppyShovel** [comment]
No Eta yet unfortunately we are both very busy, but it's coming :D

**Comment by Dartanlla** [comment]
Thanks guys!  Pull request 142 has been merged and OWS 2 is now officially recommending PostgreSQL as the primary database technology of OWS 2.  In the future, as we split out repositories into separate storage, there may be other recommended database technologies, but for the current unified database PostgreSQL is the primary one.  MSSQL will continue to be officially supported in the near future.  MySQL is still community supported.

**Comment by Dartanlla** [comment]
Complete.
