### ISSUE TITLE
compile error Argument 2: cannot convert from 'string' to 'OWSData.Models.StoredProcs.AddOrUpdateCustomCharacterData'	OWSCharacterPersistence

### ISSUE THREAD

**Issue by iiCornwallis** [Dartanlla/OWS#19]
It's likely too that I'm compiling wrong, but it won't let me past this. i'm on windows 10. OWSCharacterPersistence is the only one I can't get to compile. I looked into the error and I was having trouble finding a solution, I'll edit if I do.

**Comment by pedrohusky** [comment]
How are you compiling? Right now I'm using `Development Editor` and just pressing play inside the project VS (you must generate the VS files trough right click in the project).

**Comment by Dartanlla** [comment]
OWSCharacterPersistence is a currently unused project that is under development.  I just checked in an update to temporarily remove the syntax error so that the project can compile, but the project is not needed.  If you use the normal Docker Compose build process, the project is not include and won't throw the error.  Now with this update, it won't throw the error even if you do happen to compile the unused OWSCharacterPersistence project.
