### ISSUE TITLE
windows docker mssql image error

### ISSUE THREAD

**Issue by johnfenton1980** [Dartanlla/OWS#36]
when building docker, get the following error below .. OS being used windows server 2019, this error is given when using

docker-compose -f docker-compose.yml -f docker-compose.override.windows.yml up -d --build --force-recreate

error:::

Step 1/9 : FROM mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04
2017-CU24-ubuntu-16.04: Pulling from mssql/server
image operating system "linux" cannot be used on this platform
ERROR: Service 'mssql' failed to build : Build failed

when using

docker-compose -f docker-compose.yml -f docker-compose.override.windows.yml up -d

i get the same error message

**Comment by CanisHelix** [comment]
@johnfenton1980 You need to be using Docker in Linux Containers mode not Windows Containers mode. See instructions at https://docs.docker.com/desktop/windows/#switch-between-windows-and-linux-containers on how to switch if using the Docker Desktop application.

You mentioned Windows Server though, so you probably installed the Docker Enterprise edition via Powershell, this version does **NOT** support linux and you would need to remove that and install the Docker Community Edition from https://docs.docker.com/desktop/windows/release-notes/ instead.

Currently, OWS2 is in constant development and most users are using Windows 10 for development purposes (albeit Debian/Ubuntu as Rider is also an option if you are technically apt and don't mind fiddling around manually).

If you don't want to develop/debug and just want to run OWS2, I would personally suggest doing so in a Linux VM rather than Windows Server 2019.

**Comment by Dartanlla** [comment]
I talked to johnfenton1980 and he told me he resolved the issue and got it working.
